CREATE TABLE PHONG (
    MaPhong VARCHAR(10) PRIMARY KEY,
    LoaiPhong VARCHAR(50) NOT NULL,
    GiaDem DECIMAL(12,3) NOT NULL,
    MaDatHienTai VARCHAR(10)     
);


CREATE TABLE KHACH (
    MaKhach VARCHAR(10) PRIMARY KEY,
    TenKhach VARCHAR(100) NOT NULL,
    DienThoai VARCHAR(20),
    Email VARCHAR(100)
);


CREATE TABLE DATPHONG (
    MaDat VARCHAR(10) PRIMARY KEY,
    MaPhong VARCHAR(10),         
    MaKhach VARCHAR(10),
    NgayNhan TIMESTAMP NOT NULL,
    NgayTra TIMESTAMP NOT NULL
);

-- 1. FK: DATPHONG.MaKhach -> KHACH.MaKhach
ALTER TABLE DATPHONG
ADD CONSTRAINT fk_datphong_khach
FOREIGN KEY (MaKhach)
REFERENCES KHACH(MaKhach);

-- 2. FK: DATPHONG.MaPhong -> PHONG.MaPhong
ALTER TABLE DATPHONG
ADD CONSTRAINT fk_datphong_phong
FOREIGN KEY (MaPhong)
REFERENCES PHONG(MaPhong);

-- 3. FK vòng: PHONG.MaDatHienTai -> DATPHONG.MaDat
ALTER TABLE PHONG
ADD CONSTRAINT fk_phong_dat_hientai
FOREIGN KEY (MaDatHienTai)
REFERENCES DATPHONG(MaDat);