CREATE TABLE PHONG (
    MaPhong VARCHAR(10) PRIMARY KEY,
    LoaiPhong VARCHAR(50) NOT NULL,
    GiaDem DECIMAL(12,3) NOT NULL CHECK (GiaDem > 0),
    TinhTrang VARCHAR(20) NOT NULL
        CHECK (TinhTrang IN ('TRONG', 'DANG_O', 'BAO_TRI')),
    MaDatHienTai VARCHAR(10)
);

CREATE TABLE KHACH (
    MaKhach VARCHAR(10) PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    CCCD VARCHAR(12) UNIQUE,
    SDT VARCHAR(15)
);

CREATE TABLE DATPHONG (
    MaDat VARCHAR(10) PRIMARY KEY,
    MaPhong VARCHAR(10),
    MaKhach VARCHAR(10),
    NgayNhan TIMESTAMP NOT NULL,
    NgayTra TIMESTAMP
);

-- DATPHONG → KHACH
ALTER TABLE DATPHONG
ADD CONSTRAINT fk_dp_khach
FOREIGN KEY (MaKhach)
REFERENCES KHACH(MaKhach)
ON DELETE RESTRICT;

-- DATPHONG → PHONG
ALTER TABLE DATPHONG
ADD CONSTRAINT fk_dp_phong
FOREIGN KEY (MaPhong)
REFERENCES PHONG(MaPhong)
ON DELETE RESTRICT;

-- PHONG → DATPHONG (đơn hiện tại)
ALTER TABLE PHONG
ADD CONSTRAINT fk_phong_dat
FOREIGN KEY (MaDatHienTai)
REFERENCES DATPHONG(MaDat);