-- 1. Tạo các USER/ROLE
DROP ROLE IF EXISTS A, B, C, D, E;
CREATE ROLE A CREATEDB CREATEROLE LOGIN PASSWORD 'passA';  -- Owner
CREATE ROLE B LOGIN PASSWORD 'passB';
CREATE ROLE C LOGIN PASSWORD 'passC';
CREATE ROLE D LOGIN PASSWORD 'passD';
CREATE ROLE E LOGIN PASSWORD 'passE';

-- Chuyển ownership cho A
ALTER DATABASE khachsanhaui OWNER TO A;
ALTER TABLE KHACH OWNER TO A;
ALTER TABLE PHONG OWNER TO A;
ALTER TABLE DATPHONG OWNER TO A;

-- A -> B
SET ROLE A;

GRANT SELECT, INSERT, UPDATE, DELETE ON KHACH, PHONG, DATPHONG TO B WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO B WITH GRANT OPTION;

RESET ROLE;

-- A -> C
SET ROLE A;

GRANT SELECT, INSERT, UPDATE, DELETE ON KHACH, PHONG, DATPHONG TO C WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO C WITH GRANT OPTION;

RESET ROLE;

-- C → D (GRANT OPTION)
SET ROLE C;

GRANT SELECT, INSERT, UPDATE, DELETE ON KHACH, PHONG, DATPHONG TO D WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO D WITH GRANT OPTION;

RESET ROLE;

-- D → E (KHÔNG GRANT OPTION)
SET ROLE D;

GRANT SELECT, INSERT, UPDATE, DELETE ON KHACH, PHONG, DATPHONG TO E;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO E;

RESET ROLE;

-- B → E
SET ROLE B;

GRANT SELECT, INSERT, UPDATE, DELETE ON KHACH, PHONG, DATPHONG TO E WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO E WITH GRANT OPTION;

RESET ROLE;

-- A thu hồi quyền từ C
SET ROLE A;

REVOKE SELECT, INSERT, UPDATE, DELETE ON KHACH, PHONG, DATPHONG 
FROM C CASCADE;

REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM C CASCADE;

RESET ROLE;

-- Kết quả còn loại:
-- B còn tất cả quyền
-- C mất hết quyền
-- D mất hết quyền
-- E giữ nguyên quyền được nhận từ B